import { ExtraMaterial } from "./types";

interface InventoryItemType {
  img: string;
  name: string;
  qty: number;
  maxQty: number;
  SIunit: string;
  volume: number;
  amount: number;
}
interface InventoryData {
  [key: string]: InventoryItemType[];
}
// Inventory data
export const Inventory: InventoryData = {
  Livingroom: [
    {
      img: "/img/Sofa.jpg",
      name: "Two-Seater Sofa",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.205,
      amount: 7,
    },
    {
      img: "/img/CoffeeTable.jpg",
      name: "Three-Seater Sofa",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.687,
      amount: 10,
    },
    {
      img: "/img/CoffeeTable.jpg",
      name: "Four-Seater Sofa",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.928,
      amount: 12,
    },
    {
      img: "/img/CoffeeTable.jpg",
      name: "Armchair",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.9,
      amount: 5,
    },
    {
      img: "/img/CoffeeTable.jpg",
      name: "Coffee Table",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.288,
      amount: 5,
    },
    {
      img: "/img/CoffeeTable.jpg",
      name: "Small Television/TV (Less than 30)",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.0315,
      amount: 5,
    },
    {
      img: "/img/CoffeeTable.jpg",
      name: "Large Television/TV (Greater than 40)",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.084,
      amount: 10,
    },
    {
      img: "/img/CoffeeTable.jpg",
      name: "TV Stand",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.288,
      amount: 5,
    },
    {
      img: "/img/CoffeeTable.jpg",
      name: "Bookcase",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.48,
      amount: 10,
    },
    {
      img: "/img/CoffeeTable.jpg",
      name: "Rug",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.03,
      amount: 5,
    },
  ],
  Bedroom: [
    {
      img: "/img/SingleBed.jpg",
      name: "Single Bed & Mattress",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.934,
      amount: 7,
    },
    {
      img: "/img/DoubleBed.jpg",
      name: "Double Bed & Mattress",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.328,
      amount: 15,
    },
    {
      img: "/img/Table.jpg",
      name: "King size Bed & Mattress",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.994,
      amount: 20,
    },
    {
      img: "/img/DoubleBed.jpg",
      name: "Single Wardrobe",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.5663,
      amount: 15,
    },
    {
      img: "/img/Table.jpg",
      name: "Double Wardrobe",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.44,
      amount: 20,
    },
    {
      img: "/img/DoubleBed.jpg",
      name: "Tripple Wardrobe",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.699,
      amount: 30,
    },
    {
      img: "/img/Table.jpg",
      name: "Chest Of Drawers",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.5097,
      amount: 5,
    },
    {
      img: "/img/DoubleBed.jpg",
      name: "Bedside Table",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.12,
      amount: 3,
    },
    {
      img: "/img/Table.jpg",
      name: "Dressing Table",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.4914,
      amount: 5,
    },
    {
      img: "/img/Table.jpg",
      name: "Television",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.054,
      amount: 5,
    },
  ],
  Dinning: [
    {
      img: "/img/CustomItem1.jpg",
      name: "6-Seater Dining Table",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.35,
      amount: 5,
    },
    {
      img: "/img/CustomItem2.jpg",
      name: "8-Seater Dining Table",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 2.16,
      amount: 5,
    },
    {
      img: "/img/CustomItem2.jpg",
      name: "Dining Chair",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.25,
      amount: 5,
    },
    {
      img: "/img/CustomItem2.jpg",
      name: "Sideboard",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.54,
      amount: 5,
    },
    {
      img: "/img/CustomItem2.jpg",
      name: "Display Cabinet",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.8,
      amount: 5,
    },
    {
      img: "/img/CustomItem2.jpg",
      name: "Rug",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.03,
      amount: 5,
    },
  ],

  Kitchen: [
    {
      img: "/img/Refrigerator.jpg",
      name: "Fridge Freezer",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.756,
      amount: 7,
    },
    {
      img: "/img/Microwave.jpg",
      name: "American Fridge",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.134,
      amount: 15,
    },
    {
      img: "/img/Refrigerator.jpg",
      name: "Undercounter fridge",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.306,
      amount: 5,
    },
    {
      img: "/img/Microwave.jpg",
      name: "Washing Machine",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.306,
      amount: 5,
    },
    {
      img: "/img/Refrigerator.jpg",
      name: "Tumble Dryer",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.306,
      amount: 5,
    },
    {
      img: "/img/Microwave.jpg",
      name: "Microwave Oven",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.06,
      amount: 5,
    },
    {
      img: "/img/Refrigerator.jpg",
      name: "Cooker",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.324,
      amount: 5,
    },
    {
      img: "/img/Microwave.jpg",
      name: "Dishwasher",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.306,
      amount: 5,
    },
    {
      img: "/img/Refrigerator.jpg",
      name: "Kitchen Table",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.84,
      amount: 5,
    },
    {
      img: "/img/Microwave.jpg",
      name: "Bin",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.0495,
      amount: 5,
    },
  ],
  Office: [
    {
      img: "/img/Car.jpg",
      name: "Office Chair",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.588,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Desk",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.7875,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Lamp",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.02,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Display Cabinet",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.8,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Printer",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.03,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Filing Cabinet",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.39,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Computer",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.05,
      amount: 5,
    },
  ],
  Bathroom: [
    {
      img: "/img/Car.jpg",
      name: "Large Mirror",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.1,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Small Mirror",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.007,
      amount: 5,
    },
    {
      img: "/img/Car.jpg",
      name: "Bathroom Cabinet",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.09,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Bathtub",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.6375,
      amount: 5,
    },
  ],
  Garden: [
    {
      img: "/img/Car.jpg",
      name: "Garden Table",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.0125,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Garden Chair 1–2-seater",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.49,
      amount: 5,
    },
    {
      img: "/img/Car.jpg",
      name: "Garden chair 3- 5-Seater",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 1.05,
      amount: 10,
    },
    {
      img: "/img/Bike.jpg",
      name: "Lawn Mower",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.648,
      amount: 5,
    },
    {
      img: "/img/Car.jpg",
      name: "Toolbox",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.0375,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Bench",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.81,
      amount: 5,
    },
    {
      img: "/img/Car.jpg",
      name: "Parasol",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.18,
      amount: 15,
    },
    {
      img: "/img/Bike.jpg",
      name: "Bicycle",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.9,
      amount: 5,
    },
    {
      img: "/img/Car.jpg",
      name: "Exercise Bike",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.864,
      amount: 15,
    },
    {
      img: "/img/Bike.jpg",
      name: "Treadmill",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 2.016,
      amount: 15,
    },
    {
      img: "/img/Car.jpg",
      name: "Trampoline",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 6.363,
      amount: 15,
    },
    {
      img: "/img/Bike.jpg",
      name: "Swings",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 10.0,
      amount: 10,
    },
    {
      img: "/img/Car.jpg",
      name: "Potted plant (Small)",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.0353,
      amount: 5,
    },
    {
      img: "/img/Bike.jpg",
      name: "Potted plant (Large)",
      qty: 0,
      maxQty: 10,
      SIunit: "cubic meter",
      volume: 0.2356,
      amount: 10,
    },
  ],
  Boxes: [
    {
      img: "/img/CustomItem1.jpg",
      name: "Small Box",
      qty: 0,
      maxQty: 100,
      SIunit: "cubic meter",
      volume: 0.0283,
      amount: 1.5,
    },
    {
      img: "/img/CustomItem2.jpg",
      name: "Medium Box",
      qty: 0,
      maxQty: 100,
      SIunit: "cubic meter",
      volume: 0.0849,
      amount: 2.5,
    },
    {
      img: "/img/CustomItem2.jpg",
      name: "Large Box",
      qty: 0,
      maxQty: 100,
      SIunit: "cubic meter",
      volume: 0.1274,
      amount: 3.5,
    },
  ],
};

// Extra materials data
export const defaultExtraMaterials: ExtraMaterial[] = [
  { name: "Small Box", quantity: 0, price: 2 },
  { name: "Medium Box", quantity: 0, price: 3 },
  { name: "Large Box", quantity: 0, price: 4 },
];

// Floors
export const floorData = [0, 1, 2, 3, 4, 5];

// Prices in pounds
export const FLoorCost = 20; /*floor above 1*/
export const ManpowerCost = 20; /* above 1*/
export const PackagingPrice = 20;
export const UnpackagingPrice = 20;
export const LandingCost = 20;
export const UrgentPickupPrice = 40;
export const MillagePrice = 1;
