#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Building your project before committing'
npm run build ||
(
    echo '❌👷🔨❌ Your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why. 
    '
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'